name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v1
      # - name: Git Identity
      #   run: |
      #     git config --global user.name 'lumos bot'
      #     git config --global user.email 'lumos.bot@users.noreply.github.com'
      #     git remote set-url origin https://${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
      #     git checkout master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Checkout and pull branch
      #   run: git checkout "${GITHUB_REF:11}" && git pull

      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Packages
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build packages
        run: yarn build

      - name: Publish package
        run: yarn run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
